export type GeoOption = { value: string; label: string };

// List of top countries
export const countries: GeoOption[] = [
  { value: "afghanistan", label: "Afghanistan" },
  { value: "albania", label: "Albania" },
  { value: "algeria", label: "Algeria" },
  { value: "andorra", label: "Andorra" },
  { value: "angola", label: "Angola" },
  { value: "argentina", label: "Argentina" },
  { value: "armenia", label: "Armenia" },
  { value: "australia", label: "Australia" },
  { value: "austria", label: "Austria" },
  { value: "azerbaijan", label: "Azerbaijan" },
  { value: "bahamas", label: "Bahamas" },
  { value: "bahrain", label: "Bahrain" },
  { value: "bangladesh", label: "Bangladesh" },
  { value: "barbados", label: "Barbados" },
  { value: "belarus", label: "Belarus" },
  { value: "belgium", label: "Belgium" },
  { value: "belize", label: "Belize" },
  { value: "benin", label: "Benin" },
  { value: "bhutan", label: "Bhutan" },
  { value: "bolivia", label: "Bolivia" },
  { value: "bosnia", label: "Bosnia and Herzegovina" },
  { value: "botswana", label: "Botswana" },
  { value: "brazil", label: "Brazil" },
  { value: "brunei", label: "Brunei" },
  { value: "bulgaria", label: "Bulgaria" },
  { value: "burkina-faso", label: "Burkina Faso" },
  { value: "burundi", label: "Burundi" },
  { value: "cambodia", label: "Cambodia" },
  { value: "cameroon", label: "Cameroon" },
  { value: "canada", label: "Canada" },
  { value: "chad", label: "Chad" },
  { value: "chile", label: "Chile" },
  { value: "china", label: "China" },
  { value: "colombia", label: "Colombia" },
  { value: "comoros", label: "Comoros" },
  { value: "congo", label: "Congo" },
  { value: "costa-rica", label: "Costa Rica" },
  { value: "croatia", label: "Croatia" },
  { value: "cuba", label: "Cuba" },
  { value: "cyprus", label: "Cyprus" },
  { value: "czechia", label: "Czech Republic" },
  { value: "denmark", label: "Denmark" },
  { value: "djibouti", label: "Djibouti" },
  { value: "dominica", label: "Dominica" },
  { value: "dominican-republic", label: "Dominican Republic" },
  { value: "ecuador", label: "Ecuador" },
  { value: "egypt", label: "Egypt" },
  { value: "el-salvador", label: "El Salvador" },
  { value: "estonia", label: "Estonia" },
  { value: "ethiopia", label: "Ethiopia" },
  { value: "fiji", label: "Fiji" },
  { value: "finland", label: "Finland" },
  { value: "france", label: "France" },
  { value: "gabon", label: "Gabon" },
  { value: "gambia", label: "Gambia" },
  { value: "georgia", label: "Georgia" },
  { value: "germany", label: "Germany" },
  { value: "ghana", label: "Ghana" },
  { value: "greece", label: "Greece" },
  { value: "grenada", label: "Grenada" },
  { value: "guatemala", label: "Guatemala" },
  { value: "guinea", label: "Guinea" },
  { value: "guyana", label: "Guyana" },
  { value: "haiti", label: "Haiti" },
  { value: "honduras", label: "Honduras" },
  { value: "hungary", label: "Hungary" },
  { value: "iceland", label: "Iceland" },
  { value: "india", label: "India" },
  { value: "indonesia", label: "Indonesia" },
  { value: "iran", label: "Iran" },
  { value: "iraq", label: "Iraq" },
  { value: "ireland", label: "Ireland" },
  { value: "israel", label: "Israel" },
  { value: "italy", label: "Italy" },
  { value: "jamaica", label: "Jamaica" },
  { value: "japan", label: "Japan" },
  { value: "jordan", label: "Jordan" },
  { value: "kazakhstan", label: "Kazakhstan" },
  { value: "kenya", label: "Kenya" },
  { value: "kiribati", label: "Kiribati" },
  { value: "kosovo", label: "Kosovo" },
  { value: "kuwait", label: "Kuwait" },
  { value: "kyrgyzstan", label: "Kyrgyzstan" },
  { value: "laos", label: "Laos" },
  { value: "latvia", label: "Latvia" },
  { value: "lebanon", label: "Lebanon" },
  { value: "lesotho", label: "Lesotho" },
  { value: "liberia", label: "Liberia" },
  { value: "libya", label: "Libya" },
  { value: "liechtenstein", label: "Liechtenstein" },
  { value: "lithuania", label: "Lithuania" },
  { value: "luxembourg", label: "Luxembourg" },
  { value: "madagascar", label: "Madagascar" },
  { value: "malawi", label: "Malawi" },
  { value: "malaysia", label: "Malaysia" },
  { value: "maldives", label: "Maldives" },
  { value: "mali", label: "Mali" },
  { value: "malta", label: "Malta" },
  { value: "mauritania", label: "Mauritania" },
  { value: "mauritius", label: "Mauritius" },
  { value: "mexico", label: "Mexico" },
  { value: "moldova", label: "Moldova" },
  { value: "monaco", label: "Monaco" },
  { value: "mongolia", label: "Mongolia" },
  { value: "montenegro", label: "Montenegro" },
  { value: "morocco", label: "Morocco" },
  { value: "mozambique", label: "Mozambique" },
  { value: "myanmar", label: "Myanmar" },
  { value: "namibia", label: "Namibia" },
  { value: "nepal", label: "Nepal" },
  { value: "netherlands", label: "Netherlands" },
  { value: "new-zealand", label: "New Zealand" },
  { value: "nicaragua", label: "Nicaragua" },
  { value: "niger", label: "Niger" },
  { value: "nigeria", label: "Nigeria" },
  { value: "north-korea", label: "North Korea" },
  { value: "north-macedonia", label: "North Macedonia" },
  { value: "norway", label: "Norway" },
  { value: "oman", label: "Oman" },
  { value: "pakistan", label: "Pakistan" },
  { value: "palau", label: "Palau" },
  { value: "palestine", label: "Palestine" },
  { value: "panama", label: "Panama" },
  { value: "papua-new-guinea", label: "Papua New Guinea" },
  { value: "paraguay", label: "Paraguay" },
  { value: "peru", label: "Peru" },
  { value: "philippines", label: "Philippines" },
  { value: "poland", label: "Poland" },
  { value: "portugal", label: "Portugal" },
  { value: "qatar", label: "Qatar" },
  { value: "romania", label: "Romania" },
  { value: "russia", label: "Russia" },
  { value: "rwanda", label: "Rwanda" },
  { value: "saint-kitts-and-nevis", label: "Saint Kitts and Nevis" },
  { value: "saint-lucia", label: "Saint Lucia" },
  { value: "saint-vincent", label: "Saint Vincent and the Grenadines" },
  { value: "samoa", label: "Samoa" },
  { value: "san-marino", label: "San Marino" },
  { value: "saudi-arabia", label: "Saudi Arabia" },
  { value: "senegal", label: "Senegal" },
  { value: "serbia", label: "Serbia" },
  { value: "seychelles", label: "Seychelles" },
  { value: "sierra-leone", label: "Sierra Leone" },
  { value: "singapore", label: "Singapore" },
  { value: "slovakia", label: "Slovakia" },
  { value: "slovenia", label: "Slovenia" },
  { value: "solomon-islands", label: "Solomon Islands" },
  { value: "somalia", label: "Somalia" },
  { value: "south-africa", label: "South Africa" },
  { value: "south-korea", label: "South Korea" },
  { value: "south-sudan", label: "South Sudan" },
  { value: "spain", label: "Spain" },
  { value: "sri-lanka", label: "Sri Lanka" },
  { value: "sudan", label: "Sudan" },
  { value: "suriname", label: "Suriname" },
  { value: "sweden", label: "Sweden" },
  { value: "switzerland", label: "Switzerland" },
  { value: "syria", label: "Syria" },
  { value: "taiwan", label: "Taiwan" },
  { value: "tajikistan", label: "Tajikistan" },
  { value: "tanzania", label: "Tanzania" },
  { value: "thailand", label: "Thailand" },
  { value: "timor-leste", label: "Timor-Leste" },
  { value: "togo", label: "Togo" },
  { value: "tonga", label: "Tonga" },
  { value: "trinidad-and-tobago", label: "Trinidad and Tobago" },
  { value: "tunisia", label: "Tunisia" },
  { value: "turkey", label: "Turkey" },
  { value: "turkmenistan", label: "Turkmenistan" },
  { value: "tuvalu", label: "Tuvalu" },
  { value: "uganda", label: "Uganda" },
  { value: "ukraine", label: "Ukraine" },
  { value: "united-arab-emirates", label: "United Arab Emirates" },
  { value: "united-kingdom", label: "United Kingdom" },
  { value: "united-states", label: "United States" },
  { value: "uruguay", label: "Uruguay" },
  { value: "uzbekistan", label: "Uzbekistan" },
  { value: "vanuatu", label: "Vanuatu" },
  { value: "vatican-city", label: "Vatican City" },
  { value: "venezuela", label: "Venezuela" },
  { value: "vietnam", label: "Vietnam" },
  { value: "yemen", label: "Yemen" },
  { value: "zambia", label: "Zambia" },
  { value: "zimbabwe", label: "Zimbabwe" },
];

// List of popular cities globally
export const popularCities: GeoOption[] = [
  { value: "tokyo", label: "Tokyo" },
  { value: "delhi", label: "Delhi" },
  { value: "shanghai", label: "Shanghai" },
  { value: "sao-paulo", label: "São Paulo" },
  { value: "mexico-city", label: "Mexico City" },
  { value: "cairo", label: "Cairo" },
  { value: "mumbai", label: "Mumbai" },
  { value: "beijing", label: "Beijing" },
  { value: "dhaka", label: "Dhaka" },
  { value: "osaka", label: "Osaka" },
  { value: "new-york", label: "New York" },
  { value: "karachi", label: "Karachi" },
  { value: "buenos-aires", label: "Buenos Aires" },
  { value: "istanbul", label: "Istanbul" },
  { value: "kolkata", label: "Kolkata" },
  { value: "manila", label: "Manila" },
  { value: "lagos", label: "Lagos" },
  { value: "rio-de-janeiro", label: "Rio de Janeiro" },
  { value: "tianjin", label: "Tianjin" },
  { value: "kinshasa", label: "Kinshasa" },
  { value: "guangzhou", label: "Guangzhou" },
  { value: "los-angeles", label: "Los Angeles" },
  { value: "moscow", label: "Moscow" },
  { value: "shenzhen", label: "Shenzhen" },
  { value: "lahore", label: "Lahore" },
  { value: "bangalore", label: "Bangalore" },
  { value: "paris", label: "Paris" },
  { value: "bogota", label: "Bogotá" },
  { value: "jakarta", label: "Jakarta" },
  { value: "chennai", label: "Chennai" },
  { value: "lima", label: "Lima" },
  { value: "bangkok", label: "Bangkok" },
  { value: "seoul", label: "Seoul" },
  { value: "nagoya", label: "Nagoya" },
  { value: "hyderabad", label: "Hyderabad" },
  { value: "london", label: "London" },
  { value: "tehran", label: "Tehran" },
  { value: "chicago", label: "Chicago" },
  { value: "chengdu", label: "Chengdu" },
  { value: "nanjing", label: "Nanjing" },
  { value: "wuhan", label: "Wuhan" },
  { value: "ho-chi-minh-city", label: "Ho Chi Minh City" },
  { value: "luanda", label: "Luanda" },
  { value: "ahmedabad", label: "Ahmedabad" },
  { value: "kuala-lumpur", label: "Kuala Lumpur" },
  { value: "xi-an", label: "Xi'an" },
  { value: "hong-kong", label: "Hong Kong" },
  { value: "dongguan", label: "Dongguan" },
  { value: "hangzhou", label: "Hangzhou" },
  { value: "foshan", label: "Foshan" },
  { value: "shenyang", label: "Shenyang" },
  { value: "riyadh", label: "Riyadh" },
  { value: "baghdad", label: "Baghdad" },
  { value: "santiago", label: "Santiago" },
  { value: "surat", label: "Surat" },
  { value: "madrid", label: "Madrid" },
  { value: "suzhou", label: "Suzhou" },
  { value: "pune", label: "Pune" },
  { value: "harbin", label: "Harbin" },
  { value: "houston", label: "Houston" },
  { value: "dallas", label: "Dallas" },
  { value: "toronto", label: "Toronto" },
  { value: "miami", label: "Miami" },
  { value: "singapore", label: "Singapore" },
  { value: "philadelphia", label: "Philadelphia" },
  { value: "atlanta", label: "Atlanta" },
  { value: "fukuoka", label: "Fukuoka" },
  { value: "khartoum", label: "Khartoum" },
  { value: "barcelona", label: "Barcelona" },
  { value: "johannesburg", label: "Johannesburg" },
  { value: "berlin", label: "Berlin" },
  { value: "montreal", label: "Montreal" },
  { value: "san-francisco", label: "San Francisco" },
  { value: "rome", label: "Rome" },
  { value: "melbourne", label: "Melbourne" },
  { value: "sydney", label: "Sydney" },
  { value: "ankara", label: "Ankara" },
  { value: "alexandria", label: "Alexandria" },
  { value: "athens", label: "Athens" },
  { value: "nairobi", label: "Nairobi" },
  { value: "dublin", label: "Dublin" },
  { value: "amsterdam", label: "Amsterdam" },
  { value: "warsaw", label: "Warsaw" },
  { value: "prague", label: "Prague" },
  { value: "vienna", label: "Vienna" },
  { value: "munich", label: "Munich" },
  { value: "brussels", label: "Brussels" },
  { value: "budapest", label: "Budapest" },
  { value: "copenhagen", label: "Copenhagen" },
  { value: "stockholm", label: "Stockholm" },
  { value: "helsinki", label: "Helsinki" },
  { value: "lisbon", label: "Lisbon" },
  { value: "oslo", label: "Oslo" },
  { value: "zurich", label: "Zurich" },
  { value: "vancouver", label: "Vancouver" },
  { value: "calgary", label: "Calgary" },
  { value: "ottawa", label: "Ottawa" },
  { value: "wellington", label: "Wellington" },
  { value: "auckland", label: "Auckland" },
]; 